---
- name: Configure Fail2Ban
  hosts: rockyedge
  tasks:
  - name: Install fail2ban
    dnf:
      name: fail2ban
      state: latest
    become: True
  - name: Copy fail2ban configuration
    copy:
      src: /etc/fail2ban/jail.conf
      dest: /etc/fail2ban/jail.local
      remote_src: True
    become: True
  - name: Restart fail2ban
    service:
      name: fail2ban
      state: restarted
    become: True