---
- name: Configure and Harden SSH
  hosts: rockyedge
  tasks:
  - name: Check Port for SELinux Configuration
    ansible.builtin.shell:
      cmd: sudo semanage port -l | grep ssh | grep -q "3559"
    register: port_status
    ignore_errors: True
    become: True
  - name: Set New SSH Port in SELinux
    ansible.builtin.shell:
      cmd: sudo semanage port -a -t ssh_port_t -p tcp 3559
    when: port_status is failed
    become: True
  - name: Create /etc/ssh/sshd_config
    template:
      src: templates/sshd/sshd_config.j2
      dest: /etc/ssh/sshd_config
    become: True
    vars:
      sshd_port: "{{ lookup('community.general.lastpass', 'sshd_port', field='notes') }}"
  - name: Restart SSHd
    service:
      name: sshd
      state: restarted
    become: True
  - name: Permit SSH Traffic with Firewalld
    ansible.posix.firewalld:
      port: 3559/tcp
      permanent: yes
      state: enabled
    become: True
