---
- hosts: rockyedge
  name: Configure RockyLinux 
  
- name: Download and Install Packages
  import_playbook: configure-packages.yml
  vars:
    the_user: "{{ ansible_user_id }}"

- name: Configure OhMyZSH with Antibody
  import_playbook: configure-oh-my-zsh.yml
  vars:
    the_user: "{{ ansible_user_id }}"
    reset_ohmyzsh: True

- name: Configure Docker
  import_playbook: configure-docker.yml
  vars:
    the_user: "{{ ansible_user_id }}"

- name: Configure Fail2Ban
  import_playbook: configure-fail2ban.yml
  vars:
    fail2ban_max_retry: 2

- name: Configure AWScli and AWS Credentials
  import_playbook: configure-aws.yml
  vars:
    the_user: "{{ ansible_user_id }}"
    aws_access_key_id: "{{ lookup('community.general.lastpass', 'aws_access_key_id', field='notes') }}"
    aws_secret_access_key: "{{ lookup('community.general.lastpass', 'aws_secret_access_key', field='notes') }}"
    aws_region: us-west-2
    aws_output: json

- name: Configure MOTD
  import_playbook: configure-motd.yml
  vars:
    the_user: "{{ ansible_user_id }}"

- name: Spawn NGINX
  import_playbook: containers/spawn-nginx.yml

# - name: Configure Certbot
# - name: Configure Cron