---
- name: Prepare For Kubernetes
  hosts: all
  tasks:
    # try to make this idiomatic ansible in the future
  - name: Add Docker GPG Key
    ansible.builtin.shell:
      cmd: "{{ item }}"
    with_items:
      - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
    become: True
    # need to use xenial for now, but this should be updated to jammy
  - name: Add specified repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
    become: True
  - name: Update APT
    apt:
      update_cache: yes
      cache_valid_time: 3600
    become: True
  - name: Add Docker Prerequisites
    apt:
      name:
        - kubeadm
        - kubelet
        - kubectl
        - kubernetes-cni
      state: latest
    become: True
  - name: Disable Swap
    ansible.builtin.shell:
      cmd: swapoff -a
    become: True
  - name: Disable Swap in fstab (make it permanent)
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
    become: True
  - name: Modprobe br_netfilter
    community.general.modprobe:
      name: br_netfilter
      state: present
    become: True
  - name: Set IPv4 forward
    ansible.builtin.shell:
      cmd: "{{ item }}"
    with_items:
      - echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
      - echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
      - echo "net.bridge.bridge-nf-call-ip6tables=1" | sudo tee -a /etc/sysctl.conf
    become: True
  - name: Apply sysctl settings
    ansible.builtin.shell:
      cmd: sysctl --system
    become: True

