---
- name: Configure Containerd
  hosts: all
  tasks:
  - name: Add Docker Prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
    become: True
  - name: Add Docker GPG Key
    ansible.builtin.shell:
      cmd: "{{ item }}"
    with_items:
      - mkdir -p /etc/apt/keyrings
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    become: True
  - name: Update APT
    apt:
      update_cache: yes
    become: True
  - name: Add Containerd Packages
    apt:
      name:
        - containerd.io
      state: latest
    become: True
  - name: Create Containerd Configuration
    ansible.builtin.shell:
      cmd: "{{ item }}"
    with_items:
      - sudo mkdir -p /etc/containerd
      - sudo containerd config default | sudo tee /etc/containerd/config.toml
    become: True
  - name: Replace SystemdCgroup = false with SystemdCgroup = true
    replace:
      path: /etc/containerd/config.toml
      regexp: '^(\s*SystemdCgroup\s*=\s*)false$'
      replace: '\1true'
    become: True
  - name: Restart Containerd
    ansible.builtin.systemd:
      name: containerd
      state: restarted
    become: True