---
- name: Configure Fail2Ban
  hosts: rockyedge
  tasks:
  - name: Install fail2ban
    dnf:
      name: fail2ban
      state: latest
    become: True
  - name: Create /etc/fail2ban/jail.local
    template:
      src: templates/fail2ban/jail.local.j2
      dest: /etc/fail2ban/jail.local
    become: True
  - name: Restart fail2ban
    service:
      name: fail2ban
      state: restarted
    become: True