---
- name: Exfiltrate Kubernetes Config
  hosts: controlplane
  tasks:  
  - name: Copy join command to local file.
    ansible.builtin.fetch:
      src: /home/{{ ansible_user_id }}/.kube/config
      dest: ./kubeconfig
      flat: True