---
- hosts: all

- name: Download and Install Packages
  import_playbook: setup/configure-packages.yml

- name: Configure OhMyZSH with Antibody
  import_playbook: setup/configure-oh-my-zsh.yml
  vars:
    reset_ohmyzsh: True

- name: Configure Containerd
  import_playbook: setup/configure-containerd.yml
  
- name: Configure Kubernetes
  import_playbook: setup/configure-kubernetes.yml

# - name: Remove Docker
#   import_playbook: setup/remove-docker.yml

- name: Create Control Plane
  import_playbook: kubernetes/create-control-plane.yml

- name: Join Worker Nodes
  import_playbook: kubernetes/join-worker-nodes.yml

- name: Exfiltrate Kubeconfig
  import_playbook: kubernetes/exfiltrate-kube-config.yml