---
- name: Configure Docker
  hosts: all
  tasks:
    - name: Remove Container Tools
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent
      become: True
    - name: Update APT
      apt:
        update_cache: yes
      become: True
    - name: Install Required Packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
      become: True
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: True
    - name: Add Example GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/raspbian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
      become: True
    - name: Add Docker repo
      ansible.builtin.apt_repository:
        filename: docker
        repo: 'deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable'
        state: present
      become: True
    - name: Update APT
      apt:
        update_cache: yes
      become: True
    - name: Install Docker Packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      become: True